title: Chris Vogt, Software Engineer in San Francisco
description: >
  Software Engineer in San Francisco, sharing open source projects
  written in JavaScript and PHP.
banner_image_url: https://res.cloudinary.com/chrisvogt/image/upload/v1482915326/og-image_a1i3rp.png
baseurl: ''
locale: en-US
permalink: /blog/:categories/:slug
url: ''

analytics_id: UA-33558417-1

components:
  instagram: https://api.chrisvogt.me/instagram
  latest_repos: https://gh-latest-repos-fmyaneprcd.now.sh
  latest_commit:
    url: https://api.github.com/users/${username}/events/public
    username: chrisvogt
  metas: https://api.chrisvogt.me/metas
  profiles: https://api.chrisvogt.me/profiles
  quotes: https://api.chrisvogt.me/quotes
  recently_read: https://recently-read.chrisvogt.me

social:
  instagram_username: c1v0
  twitter_username: c1v0
  goodreads_link: https://www.goodreads.com/user/show/10454947-chris-vogt

strings:
  bio: >
    Chris Vogt is a software engineer who works on digital marketing products
    and lives in San Francisco. He enjoys reading science fiction, capturing
    photos and drone footage, playing piano and brewing beer.
  brand: chrisvogt.me
  name: Chris Vogt
  subhead: Software Engineer <span>in San Francisco</span>
  title: Chris Vogt â€” Software Engineer in San Francisco

theme_options:
  show_credits: true

plugins:
  - jekyll-feed

sass:
  sass_dir: ./assets/styles

exclude:
  - _build
  - design
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - bower.json
  - bower_components
  - node_modules
  - package-lock.json
  - package.json
  - vendor-packages.txt
