title: Chris Vogt — Software Engineer in San Francisco
email: 'mail@chrisvogt.me'
description:  Software Engineer in San Francisco, sharing open source projects written in JavaScript and PHP.
banner_image_url: https://res.cloudinary.com/chrisvogt/image/upload/v1482915326/og-image_a1i3rp.png
baseurl: '' # the subpath of your site, e.g. /blog
url: '' # the base hostname & protocol for your site, e.g. http://example.com

destination: './_build'
sass:
  sass_dir: ./_stylesheets
  style: compressed

analytics_id: UA-33558417-1

social:
  instagram_username: c1v0
  twitter_username: c1v0
  goodreads_link: https://www.goodreads.com/user/show/10454947-chris-vogt

strings:
  headline: Chris Vogt
  subhead: Software Engineer <span>in San Francisco</span>
  title: Chris Vogt — Software Engineer in San Francisco

theme_options:
  show_credits: true

# Build settings
sass:
  sass_dir: ./assets/styles

exclude:
  - design
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - bower.json
  - bower_components
  - node_modules
  - package-lock.json
  - package.json
  - vendor-packages.txt
